"""add_player_average_columns

Revision ID: 15087aee213e
Revises: a1b2c3d4e5f6
Create Date: 2026-08-07 09:29:57.740844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15087aee213e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_a_average', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('player_b_average', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('player_b_average')
        batch_op.drop_column('player_a_average')

    # ### end Alembic commands ###
