"""add_match_scores

Revision ID: 1a77da3178db
Revises: e76c7fb306dd
Create Date: 2026-07-21 20:08:03.668228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a77da3178db'
down_revision: Union[str, None] = 'e76c7fb306dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {col['name'] for col in inspector.get_columns('matches')}

    with op.batch_alter_table('matches', schema=None) as batch_op:
        if 'player1_score' not in existing_columns:
            batch_op.add_column(sa.Column('player1_score', sa.Integer(), nullable=True))
        if 'player2_score' not in existing_columns:
            batch_op.add_column(sa.Column('player2_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('player2_score')
        batch_op.drop_column('player1_score')

    # ### end Alembic commands ###
